/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.4
 * Generated at: 2025-03-22 16:05:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import uk.ac.ucl.model.domain.Note;
import java.util.List;
import java.util.ArrayList;

public final class editNote_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("uk.ac.ucl.model.domain.Note");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/meta.jsp", out, false);
      out.write("\n");
      out.write("  <title>Edit Note</title>\n");
      out.write("  <style>\n");
      out.write("    .form-container { max-width: 800px; margin: 20px auto; }\n");
      out.write("    .form-group { margin-bottom: 15px; }\n");
      out.write("    label { display: block; margin-bottom: 5px; font-weight: bold; }\n");
      out.write("    input[type=\"text\"], textarea { width: 100%; padding: 8px; box-sizing: border-box; }\n");
      out.write("    textarea { min-height: 200px; }\n");
      out.write("    .buttons { margin-top: 20px; }\n");
      out.write("    .button { padding: 8px 15px; margin-right: 10px; cursor: pointer; }\n");
      out.write("  </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/header.jsp", out, false);
      out.write("\n");
      out.write("<div class=\"main\">\n");
      out.write("  ");

    Note note = (Note) request.getAttribute("note");
    boolean isNew = (note == null);

    if (isNew) {
      note = new Note("", "", "", "",  new ArrayList<>());
  
      out.write("\n");
      out.write("  <h2>Create New Note</h2>\n");
      out.write("  ");
 } else { 
      out.write("\n");
      out.write("  <h2>Edit Note</h2>\n");
      out.write("  ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("  <div class=\"form-container\">\n");
      out.write("    <form method=\"post\" action=\"editNote.html\">\n");
      out.write("      ");
 if (!isNew) { 
      out.write("\n");
      out.write("      <input type=\"hidden\" name=\"id\" value=\"");
      out.print( note.getId() );
      out.write("\">\n");
      out.write("      ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("      <div class=\"form-group\">\n");
      out.write("        <label for=\"header\">Title:</label>\n");
      out.write("        <input type=\"text\" id=\"header\" name=\"header\" value=\"");
      out.print( note.getHeader() );
      out.write("\" required>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <div class=\"form-group\">\n");
      out.write("        <label for=\"textContent\">Content:</label>\n");
      out.write("        <textarea id=\"textContent\" name=\"textContent\">");
      out.print( note.getTextContent() != null ? note.getTextContent() : "" );
      out.write("</textarea>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <div class=\"form-group\">\n");
      out.write("        <label for=\"url\">URL:</label>\n");
      out.write("        <input type=\"text\" id=\"url\" name=\"url\" value=\"");
      out.print( note.getUrl() != null ? note.getUrl() : "" );
      out.write("\">\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <div class=\"form-group\">\n");
      out.write("        <label for=\"imagePath\">Image Path:</label>\n");
      out.write("        <input type=\"text\" id=\"imagePath\" name=\"imagePath\" value=\"");
      out.print( note.getImagePath() != null ? note.getImagePath() : "" );
      out.write("\">\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <div class=\"form-group\">\n");
      out.write("        <label for=\"categories\">Categories (comma separated):</label>\n");
      out.write("        <input type=\"text\" id=\"categories\" name=\"categories\"\n");
      out.write("               value=\"");
      out.print( note.getCategories() != null ? String.join(", ", note.getCategories()) : "" );
      out.write("\">\n");
      out.write("        <small>Enter categories separated by commas (e.g., work, personal, important)</small>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <div class=\"buttons\">\n");
      out.write("        <input type=\"submit\" value=\"Save Note\" class=\"button\">\n");
      out.write("        <a href=\"");
      out.print( isNew ? "noteIndex.html" : "viewNote.html?id=" + note.getId() );
      out.write("\" class=\"button\">Cancel</a>\n");
      out.write("      </div>\n");
      out.write("    </form>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/footer.jsp", out, false);
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
